{% set name = "my-jupyter-shared-drive" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/my_jupyter_shared_drive-{{ version }}.tar.gz
  sha256: cec3f0515c286c5bb0b3db144f1c15329b4c6c43a0ccf0ea43d7c644a6be9496

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
    - hatchling >=1.4.0
    - hatch-jupyter-builder >=0.5
    - jupyterlab >=4
  run:
    - python >={{ python_min }}

test:
  imports:
    - my_jupyter_shared_drive
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupyter/my-shared-docprovider-extension/package.json                             # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyter\\my-shared-docprovider-extension\\package.json (exit 1)          # [win]

about:
  home: https://github.com/davidbrochart/my-jupyter-shared-drive
  summary: 'A shared drive that you want to keep for yourself :)'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinRenou
